//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyMClothing.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUCTO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PRODUCTO()
        {
            this.DETALLE_VENTA = new HashSet<DETALLE_VENTA>();
            this.RESENA = new HashSet<RESENA>();
        }
    
        public int ID_PRODUCTO { get; set; }
        public int ID_CATEGORIA { get; set; }
        public int ID_TEMPORADA { get; set; }
        public string NOMBRE_PRODUCTO { get; set; }
        public string DESCRIPCION { get; set; }
        public decimal PRECIO_PRODUCCION { get; set; }
        public decimal PRECIO_VENTA { get; set; }
        public decimal PROMEDIO_RESENA { get; set; }
        public int STOCK_TOTAL { get; set; }
        public string URL_IMAGEN { get; set; }
        public int ESTADO { get; set; }
        public string TALLA { get; set; }
        public Nullable<int> DESCUENTO { get; set; }
    
        public virtual CATEGORIA CATEGORIA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DETALLE_VENTA> DETALLE_VENTA { get; set; }
        public virtual TEMPORADA TEMPORADA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RESENA> RESENA { get; set; }
    }
}
